name: Run Python Scripts Automatically in Pairs

on:
  schedule:
    # 台灣時間每天凌晨12:00執行（UTC時間16:00）
    - cron: '0 18 * * *'

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 2  # 一次最多執行兩個腳本
      matrix:
        script:
          - 'code/Tokyo/tokyo.py'
          - 'code/Sydney/sydney.py'
          - 'code/HongKong/hongkong.py'
          - 'code/Losangeles/losangeles.py'
          - 'code/London/london.py'
          - 'code/Newyork/newyork.py'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium requests

    - name: Install ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-chromedriver
        sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver

    - name: Run script
     
