name: Run Python Scripts Automatically in Pairs

on:
  schedule:
    # 台灣時間
    - cron: '0 8 * * *'

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 2  # 一次最多執行兩個腳本
      matrix:
        script:
          - 'code/Tokyo/tokyo.py'
          - 'code/Tokyo/tokyo_business.py'
          - 'code/Sydney/sydney.py'
          - 'code/Sydney/sydney_business.py'
          - 'code/HongKong/hongkong.py'
          - 'code/HongKong/hongkong_business.py'
          - 'code/LosAngeles/losangeles.py'
          - 'code/LosAngeles/losangeles_business.py'
          - 'code/London/london.py'
          - 'code/London/london_business.py'
          - 'code/NewYork/newyork.py'
          - 'code/NewYork/newyork_business.py'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium requests

    - name: Install ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install --reinstall -y chromium-chromedriver
        if [ -L /usr/bin/chromedriver ]; then
          sudo rm /usr/bin/chromedriver  # 如果存在符號連結，則刪除
        fi
        sudo ln -sf /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver || true  # 強制創建新的符號連結

    - name: Set ChromeDriver Path
      run: echo "CHROMEWEBDRIVER=/usr/bin" >> $GITHUB_ENV  # 設置環境變量

    - name: Run script
      run: |
        python ${{ matrix.script }}  # 動態運行 Python 腳本

    - name: Commit results to GitHub
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'actions@github.com'
        git add data/
        git commit -m "Auto-commit flight data results"
        git push https://${{ secrets.GH_TOKEN }}@github.com/ching1223/flight_data.git HEAD:main