name: Run Python Scripts Automatically in Pairs

on:
  schedule:
    # 台灣時間每天凌晨1:55執行（UTC時間17:55）
    - cron: '0 19 * * *'

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 2  # 一次最多執行兩個腳本
      matrix:
        script:
          - 'code/Tokyo/tokyo.py'
          - 'code/Sydney/sydney.py'
          - 'code/HongKong/hongkong.py'
          - 'code/Losangeles/losangeles.py'
          - 'code/London/london.py'
          - 'code/Newyork/newyork.py'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium requests

    - name: Install ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-chromedriver
        if [ -L /usr/bin/chromedriver ]; then
          sudo rm /usr/bin/chromedriver  # 如果存在符號連結，則刪除
        fi
        sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver

    - name: Run script
      run: |
        python ${{ matrix.script }}  # 動態運行 Python 腳本
